### ISSUE TITLE
TRANSCRIPT demo

### ISSUE THREAD

**Issue by piaohai** [youngwoo-yoon/Co-Speech_Gesture_Generation#5]
hi,guys, would you pleases provide some TRANSCRIPT demo,i want to run test, tks.

**Comment by youngwoo-yoon** [comment]
A way to synthesize gestures from a plain text is not available in this repository, because the code is assumed to be run with the GENEA workshop dataset. I recommend you to modify `SubtitleWrapper` class to support your own transcripts. Note that you should provide timestamps for each word.  

You might be interested in our new work [Gesture-Generation-from-Trimodal-Context](https://github.com/ai4r/Gesture-Generation-from-Trimodal-Context) which is a follow-up work of this repository and provides what you want, synthesizing gestures from a plain text, so please check it out.
